version: '3'

services:
    spark-master:
        image: bde2020/spark-master:2.4.0-hadoop2.7
        container_name: spark-master
        ports:
            - "8080:8080"
            - "7077:7077"
        environment:
            - INIT_DAEMON_STEP=setup_spark
            - "constraint:node==<yourmasternode>"
            - PYSPARK_PYTHON=python3
    spark-worker-1:
        #image: bde2020/spark-worker:2.4.0-hadoop2.7
        build: worker
        container_name: spark-worker-1
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
            - "constraint:node==<yourmasternode>"
            - PYSPARK_PYTHON=python3
    spark-worker-2:
        #image: bde2020/spark-worker:2.4.0-hadoop2.7
        build: worker
        container_name: spark-worker-2
        depends_on:
            - spark-master
        ports:
            - "8082:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
            - "constraint:node==<yourworkernode>"
            - PYSPARK_PYTHON=python3
